### ISSUE TITLE
Idea: Support $n placeholders

### ISSUE THREAD

**Issue by Skeeve** [nullism/bqb#27]
Currently you support the `?` placeholder. Would it be an option to also support `$n` placeholders?

Sometimes I need one value at more than one place in a query. For example in unions:

```sql
	// simplified example
	q := bqb.New( /* sql */ `
        SELECT name
            , email 
        FROM users 
        WHERE subscription = ?
        UNION
        SELECT client_name AS name
        FROM clients
        WHERE subscription = ?
	`, subscription, subscription)
```

Would it be an option to support $1 here?

```sql
	// simplified example
	q := bqb.New( /* sql */ `
        SELECT name
            , email 
        FROM users 
        WHERE subscription = $1
        UNION
        SELECT client_name AS name
        FROM clients
        WHERE subscription = $1
	`, subscription)
```

**Comment by nullism** [comment]
Hi Skeeve!

I see what you're getting at, but I don't think we want to do this because the internals would require substantial changes.

It does seem slightly nicer to do `"$1 $1", foo` vs `"? ?", foo, foo` but there is really no performance difference if using references, and to add this syntax sugar we would require special handling for non-postgres in that we'd need to re-duplicate the parameters anyway. 

Let me think on this a bit more and see if there's a quick win here. Thanks for the suggestion!

**Comment by nullism** [comment]
Yeah the additional processing does slow it down a bit, and we also need to check for mismatch params which is easy with `?` since we just do `len` compare, but kind of slow for named parameters, so I think I'm not going to do this. Appreciate the issue and apologies for not having a good solution!

**Comment by Skeeve** [comment]
Fair enough. Thanks for trying.
