### ISSUE TITLE
Performance issue with Query.ToMysql

### ISSUE THREAD

**Issue by yuanliuGeo** [nullism/bqb#7]
I have a query with over 10000 parameters in _"names"_, unfortunately, I have a usecase with 10000 ids in IN statement.  And query.ToMysql() takes 3 mins to return the results. Is there any recommendation for the number of parameters?

My code is like:
	
	deviceUUIDFromValue := bqb.New(`
	SELECT device_id FROM devices_parameters 
	WHERE TYPE = ?
	AND value IN (?)`, sourceTypeMap[type], names)

	filterForEnvOperator := createEnvIDQuery(request.EnvOperatorMap)

	deviceUUIDFromOperator := bqb.New(`
	SELECT device_id FROM devices_operators 
	WHERE device_id IN (?) ?`, deviceUUIDFromValue, filterForEnvOperator)

	query := bqb.New(`
	SELECT t1.data, t2.value, t3.operator_id, t3.env_id FROM audit_device t1 
	JOIN devices_parameters t2 ON t2.device_id = t1.device_id 
	JOIN devices_operators t3 ON t3.device_id = t1.device_id
	WHERE t1.device_id IN (?)
	ORDER BY t1.id DESC`, deviceUUIDFromOperator)

	sql, params, err := query.ToMysql()

**Comment by nullism** [comment]
Hi there!

I think I need some more details, since on my machine 10,000 items takes less than 1 second, even if I nest queries within queries.

Is it possible that the actual database call is what is taking a long time, and not building the query? 

For example, if you just run the following:

```go
	var names []string
	for i := 0; i < 10000; i++ {
		names = append(names, fmt.Sprintf("n%d", i))
	}
	q := bqb.New("TEST IN (?)", names)

	start := time.Now()
	q.ToMysql()
	delta := time.Since(start)
	fmt.Printf("request took %vs\n", delta.Seconds())
```

output for me
```
request took 0.8661975s
```

Does that run reasonably fast for you?

**Comment by yuanliuGeo** [comment]
When I ran your code locally, it shows similar to your output. But when moving your code to k8s pod with 250m CPU. The output is 87 secs ish. After I change to 1000m CPU, it turns to 11 secs. I assume that call is a CPU-intense call for 10,000 items. And I need more CPU resources to run it.

**Comment by nullism** [comment]
Hmmm, yeah, that's to be expected I'd say. Though I am surprised it's that slow, but it doesn't seem unreasonably slow for what it's doing.

As a test I took out what I suspected was the expensive call, which is `strings.Replace`. It needs to do this to use the appropriate operator when you call `ToMysql` or `ToPgsql`, and since it doesn't know which operator you'll be using ahead of time the only way to change it is to replace it. Open to suggestions, but that is the CPU intensive portion from my tests. 

I suspect, but don't know, that any query builder which allows a query to be converted to multiple formats _after_ it's built would have the same issue, but if you know of one that doesn't I'd be happy to take a look and try to fix it. 

Sorry about that, I think it's just the nature of how it works at the moment but will think about some potential optimizations.

**Comment by nullism** [comment]
After a bit more thought, would it make sense to use a JSON operator here? 

Example: https://go.dev/play/p/Pj2TET5Ta7s

Basically, instead of MySQL's `WHERE value IN (?,?,?...)` it'd be `WHERE value MEMBER OF (?)` with `?` being a JSON array. Seems to be much faster for building the query, but not sure if actually running the query would be faster (or if that's exactly the right syntax).

**Comment by nullism** [comment]
Aha!

So this will not help postgres, but mysql and any `?` syntax DB implementation will now be much faster. It turns out that I was doing `strings.Replace` one at a time even when it wasn't necessary. 

I just cut a release `v1.3.1` with this change in it. Could you try that out and let me know?

**Comment by yuanliuGeo** [comment]
Hi, 

I did a quick test. Yes, that works fast. I will do a bit more testing to verify it, but it looks good to me so far. Thanks a lot.

**Comment by nullism** [comment]
Nice, happy to help! Feel free to re-open if you notice any issues with that build. Thanks for pointing out the issue!
